#names of sample directories containing the fastq directories
samples: "samples.csv"

params:
    adapters: "ref/adapters.fa"
    bbduk: "ktrim=r k=23 mink=11 hdist=1 qtrim=w trimq=10 minlen=36 entropy=0.01 entropywindow=50 entropyk=5 tbo"
    ref: "ref/HIV_B.K03455.HXB2.fasta"
    consiter: "-i 5 -p 1 -xmx 50 --noindel"

threads:
    bbduk: 16
    spades_ec: 16
    consiter: 16
