#names of sample directories containing the fastq directories
samples:
    ["SRR8209080"]

params:
    adapters: "ref/adapters.fa"
    bbduk: "ktrim=r k=23 mink=11 hdist=1 qtrim=w trimq=10 minlen=36 entropy=0.01 entropywindow=50 entropyk=5 tbo"
    #trinity: "--max_memory 100G"
    #blast_db: "/hpcdata/bcbb/stern/databases/mouse_protein_db.faa"
    #pfam_db: "/hpcdata/bcbb/stern/databases/Pfam-A.hmm"

threads:
    bbduk: 16
    spades_ec: 16
