$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  kraken_db:
    type: object
    properties:
      name:
        type: string
    required:
      - name
